version: 2.1

orbs:
  architect: giantswarm/architect@9.5.5

workflows:
  build:
    jobs:
    - architect/go-build:
        context: architect
        name: go-build
        binary: konfigure
        architectures: "linux/amd64,linux/arm64,darwin/amd64,darwin/arm64,windows/amd64,windows/arm64"
        filters:
          tags:
            only: /^v.*/
        pre-steps:
        - run:
            command: apk add --no-cache gnupg

    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        platforms: "linux/amd64,linux/arm64"
        requires:
        - go-build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master

    - architect/upload-release-assets:
        context: architect
        name: upload-release-assets
        binary: konfigure
        requires:
        - go-build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
