apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
stringData:
  secret.yaml: |
    service:
      gitHub:
        token: {{ .Values.Installation.V1.Secret.ConfigController.GitHub.Token | quote }}

